adding content for run-tests

diff --git a/tests/cpp/run-tests b/tests/cpp/run-tests
--- a/tests/cpp/run-tests
+++ b/tests/cpp/run-tests
@@ -1,1 +1,39 @@
 #!/usr/bin/bash
+
+set -e
+
+Reset='\033[0m'
+Black='\033[0;30m'
+Red='\033[0;31m'
+Green='\033[0;32m'
+Yellow='\033[0;33m'
+Blue='\033[0;34m'
+Purple='\033[0;35m'
+Cyan='\033[0;36m'
+White='\033[0;37m'
+
+passed=0
+failed=0
+
+for f in out/*-test ; do
+    "./${f}"
+    code=$?
+
+    echo -ne "TEST ${Cyan}${f}${Reset} "
+    if [[ $code != 0 ]]; then
+        echo -e "${Red}FAILED${Reset}"
+        ((failed=failed+1))
+    else
+        echo -e "${Green}PASSED${Reset}"
+        ((passed=passed+1))
+    fi
+done
+
+echo
+echo -e "${Cyan}${passed}${Reset} passed, ${Purple}${failed}${Reset} failed"
+
+if [[ $failed != 0 ]]; then
+    exit 1
+else
+    exit 0
+fi
